### ISSUE TITLE
Always On Display triggers onscreen_mode

### ISSUE THREAD

**Issue by linyinfeng** [shadow3aaa/perapp-rs#2]
When the "Always On Display" feature is turned on, `preapp-rs` can not enter `offscreen_mode`, since the screen will never be turned off... Also, when a notification arrives and the screen is turned on, it enters `onscreen_mode` too. Is this an intended behavior?

I'm not familiar with Android development. I checked the source code, and it tests  `screenState=SCREEN_STATE_ON` on the output of `dumpsys window policy`. I found that there is another property in `dumpsys window policy`, `interactiveState=INTERACTIVE_STATE_AWAKE`, maybe testing this property is more reasonable?

**Comment by shadow3aaa** [comment]
> When the "Always On Display" feature is turned on, `preapp-rs` can not enter `offscreen_mode`, since the screen will never be turned off... Also, when a notification arrives and the screen is turned on, it enters `onscreen_mode` too. Is this an intended behavior?
> 
> I'm not familiar with Android development. I checked the source code, and it tests  `screenState=SCREEN_STATE_ON` on the output of `dumpsys window policy`. I found that there is another property in `dumpsys window policy`, `interactiveState=INTERACTIVE_STATE_AWAKE`, maybe testing this property is more reasonable?
> 

I turned on AOD on my device and did some testing:
```
# sdcard sleep 3s && dumpsys window policy | grep interactiveState=
      interactiveState=INTERACTIVE_STATE_SLEEP
# sdcard sleep 3s && dumpsys window policy | grep screenState=
      screenState=SCREEN_STATE_ON
```
It seems that `interactiveState=INTERACTIVE_STATE_SLEEP` is indeed more in line with the design goal than `screenState=SCREEN_STATE_ON`
